<?php

namespace AppBundle\Repository;

/**
 * SpecialPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
